shopApp/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'
urlpatterns = [
    path('category/<str:category_slug>', views.ProductList, name='ProductListByCategory'),
    path('product/<str:product_slug>/<int:id>', views.ProductDetail, name='ProductDetail'),
    path('product/cart/', views.ShowCartProduct, name='ShowCartProduct'),
    path('ajax/cart/remove/product', views.RemoveProductFromCart, name='RemoveProductFromCart'),
    path('ajax/cart/chage/product/count', views.ChangeProductCountInCart, name='ChangeProductCountInCart'),
    path('', views.ProductList, name='ProductList'),
]

shopApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('shop.urls'), name = 'shop'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopApp/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])

    def __str__(self):
        return self.name


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория", on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', null=True, blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    count_in_cart = 0

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.slug, self.id])

# Модель корзина пользователя
class Cart(models.Model):
    product = models.ForeignKey(Product, related_name='cart', verbose_name="Корзина", on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, blank=False, related_name='created_by', editable=False, on_delete=models.CASCADE)
    date_from = models.DateTimeField(auto_now=True)


# Модель коментарий к продукту
class ProductComment(models.Model):
    product = models.ForeignKey(Product, related_name='product_comment', verbose_name="Продукт", on_delete=models.CASCADE)
    comment = models.TextField(blank=False, verbose_name="Коментарий")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления коментария")

    def __str__(self):
        return self.comment


# Модель рейтинг товара TODO
class Rating(models.Model):
    product = models.ForeignKey(Product, related_name='rating', verbose_name="Рейтинг", on_delete=models.CASCADE)

shopApp/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Category, Product, ProductComment, Cart
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import JsonResponse


def ProductList(request, category_slug=None, products=None, is_cart=False):
    """
     Страница с товарами
     :param request - запрос
     :param category_slug - название категории
     :param products - список продуктов которые необходимо отобразить
     :param is_cart - флаг, true если просматриваем содержимое корзины, false в обратном случаи
    """
    category = None
    categories = Category.objects.all()
    if products is None:
        products = Product.objects.filter(available=True)
    cart_count = get_cart_count(request)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'cartCount': cart_count,
        'is_cart': is_cart
    })


def get_cart_count(request):
    """
     Получить общее колличество товаров в корзине пользователя
    """
    if request.user.is_authenticated:
        return Cart.objects.filter(created_by=request.user).distinct('product_id').count()


def ProductDetail(request, id, product_slug):
    """
     Страница с описанием товара
    """
    product = get_object_or_404(Product, id=id, slug=product_slug, available=True)
    product_comments = ProductComment.objects.filter(product_id=id).order_by('-created')
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=product.category_id)
    return render(request, 'shop/product/detail.html', {
        'product': product,
        'product_comments': product_comments,
        'categories': categories,
        'category': category,
    })


def AddProductToCart(request, id, product_slug):
    """
     Добавить продукт в корзину
    """
    add_product_to_cart(id, request)
    return ProductList(request)


def add_product_to_cart(id, request):
    """
    Увеличивает колличество определенного продукта
    :param id: идентификатор продукта
    :param request:  запрос
    :return:
    """
    product = get_object_or_404(Product, id=id, available=True)
    product.stock -= 1
    product.save()
    cart = Cart()
    cart.product = product
    cart.created_by = request.user
    cart.save()


def remove_product_from_cart(request, product_id):
    """
     Удалить продукт из корзины пользователя
     Данные метод удаляет продукт из корзины пользователя и добавляет
     удаленное коллличество товара на склад
     :param product_id - идентификатор товара
    """
    product = get_object_or_404(Product, id=product_id)
    product.stock += Cart.objects.filter(created_by=request.user, product_id=product_id).count()
    product.save()
    Cart.objects.filter(product_id=product_id, created_by=request.user).delete()
    pass


@csrf_exempt
@login_required(login_url='/accounts/login/')
def ShowCartProduct(request):
    """
    Посмотреть корзину с товарами
    """
    cart = Cart.objects.filter(created_by=request.user)
    product_ids_in_cart = [item.product_id for item in cart]
    products = Product.objects.filter(id__in=set(product_ids_in_cart))

    # для каждого продукта получаем его колличество в корзине
    for product in products:
        product.count_in_cart = product_ids_in_cart.count(product.id)

    return ProductList(request, products=products, is_cart=True)


@csrf_exempt
@login_required(login_url='/accounts/login/')
def RemoveProductFromCart(request):
    """
    Удалить товар из корзины
    """
    remove_product_from_cart(request, request.POST['id'])

    return JsonResponse({"cartCount": get_cart_count(request)})


def dicreaseProductCountInCartByOne(request, product_id):
    """
    Уменьшить колличество товара в корзине на 1
    :param request: запрос
    :param product_id: идентификатор товара который надо уменьшить
    :return:
    """
    cart = Cart.objects.filter(created_by=request.user, product_id=product_id).earliest('date_from')
    cart.delete()


@csrf_exempt
@login_required(login_url='/accounts/login/')
def ChangeProductCountInCart(request):
    """
    Данный метод изменяет колличество конкретного товара в корзине,
    уменьшает на один или увеличивает, возвращает новое колличество измененого товара в
    корзине и общее колличество товара в корзине как результат
    :param request: запрос
    :return: product_count оставшиеся колличество товара
    """

    product_id = request.POST['id']
    operation = request.POST['operation']

    if operation == "add":
        add_product_to_cart(product_id, request)
    elif operation == "remove":
        dicreaseProductCountInCartByOne(request, product_id)
    else:
        raise AttributeError('undefined operation' + operation)

    product_count = Cart.objects.filter(created_by=request.user, product_id=product_id).count()
    return JsonResponse({"productCount": product_count, "cartCount": get_cart_count(request)})

shopApp/shop/templates/shop/category/category.html
<div id="sidebar">
    <h3>Категории</h3>
    <div class = "list-group">
        <a {% if not category %} class="list-group-item list-group-item-action active" {% endif %} class="list-group-item list-group-item-action"
            href="{% url "shop:ProductList" %}">
            Все
        </a>
        {% for cat in categories %}
        <a {% if cat.pk == category.pk %}
                class="list-group-item list-group-item-action active"
           {% endif %}
             class="list-group-item list-group-item-action"
             href="{{ cat.get_absolute_url }}">{{ cat.name }}
        </a>
        {% endfor %}
    </div>
</div>

shopApp/shop/templates/shop/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</head>
<body>
    <div class="container-fluid">
        <div class = "row">
            <div class="col-md-2"></div>
            <section id="header" class="text-center col-md-8" >
                <div>
                    Мой Онлайн-Магазин
                </div>
                <div>
                    <div>
                        {% if user.is_authenticated %}
                            <a href = "{% url "shop:ShowCartProduct" %}">В вашей корзине <span id = "cartCount">{{cartCount}}</span> товаров</a>
                        {% else %}
                            <p>Ваша необходимо авторизироваться</p>
                        {% endif %}
                    </div>
                </div>
            </section>
            <section class="col-md-2">
                <div>
                    {% if user.is_authenticated %}
                    <p>User: {{ user.get_username }}</p>
                        <p><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></p>
                    {% else %}
                        <p><a href="{% url 'login'%}?next={{request.path}}">Login</a></p>
                    {% endif %}
                </div>
            </section>
        </div>
        <div class="row">
            <section id="category" class="col-md-2 text-center">
                {% include "shop/category/category.html" %}
            </section>
            <section id="content" class="col-md-8">
                {% block content %}{% endblock %}
            </section>
        </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

shopApp/shop/templates/shop/product/detail.html
{% extends "shop/index.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div>
    <div class="col-sm-4">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}"
             class="img-responsive">
    </div>
    <div class="col-sm-4">
        <h2>{{ product.name }}</h2>
        <div>
            <p class="price">
                {{ product.price }} руб.
            </p>
            <div>
                <h4>Описание</h4>
                <span>
                {{ product.description | linebreaks}}
             </span>
            </div>
        </div>
        {% if product_comments %}
        <div>
            <h4>Отзывы:</h4>
            {% for comment in product_comments %}
            <div class="card">
                <h5 class="card-title">Пользователь:</h5>
                <p>{{comment.created}}</p>
                <span>
                    {{ comment.comment }}
                </span>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

shopApp/shop/templates/shop/product/list.html
{% extends 'shop/index.html' %}
{% load static %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}
{% block content %}
  <div id="main" class="text-center">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="row">
      {% for product in products %}
        <div class="col-sm-4" id = "product">
          <div class="col-sm-11 card">
            <a href="{{ product.get_absolute_url }}">
              <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{ product.name }}</h5>
              <p class="card-text">Цена : {{ product.price }} руб.</p>
              {% if is_cart %}
              <div class = "justify-content-center">
                <div class = "row">                    
                  <p class="card-text">Колличество : <span id = "productCount_{{ product.id }}">{{product.count_in_cart}}</span> </p>
                  <a href="#" role="button" class="" 
                          onclick="CartModule.changeProductCountInCart({{ product.id }}, 'add') ;return false;">
                          <img style="margin : 5px; width: 12px" src="{% static '/icon/plus.svg' %}" alt="plus"></a>
                  <a href="#" role="button" class="" 
                          onclick="CartModule.changeProductCountInCart({{ product.id }}, 'remove');return false;">
                          <img style="margin : 5px; width: 12px" src="{% static '/icon/minus.svg' %}" alt="minus"></a>
                </div>
              </div>
              {% else %}
                <p class="card-text">Остаток : {{ product.stock }}</p>
              {% endif %}
              <div class="btn-group btn-group-toggle">
                <a href="{{ product.get_absolute_url }}" role="button" class="btn btn-outline-primary btn-sm">Подробнее</a>
                {% if user.is_authenticated %}
                  {% if is_cart %}
                    <a href="#" role="button" class="btn btn-outline-danger btn-sm" 
                          onclick="CartModule.removeProductFromCart({{ product.id }}, this);return false;">Удалить из корзины</a>
                  {% else %}
                    <a href="#" role="button" class="btn btn-outline-success btn-sm"
                          onclick="CartModule.changeProductCountInCart({{ product.id }}, 'add'); return false" >Добавить в корзину</a>
                  {% endif %}
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}